### ISSUE TITLE
Add script for creating EC2 + mounted EBS

### ISSUE THREAD

**Issue by afred** [WGBH/aws-wrapper#41]
As a DevOps
I can create a combo of EC2 instance with a mounted EBS volume
independently of anything else
in order to create one-off instances for demos, testing provisioning scripts, etc.

**Comment by mccalluc** [comment]
@afred: `build.rb` without `--setup_load_balancer` goes partway there... but you just want to create one machine, right? Is there anything else missing?

**Comment by afred** [comment]
that's all I think, the user story pretty much sums it up.
