### ISSUE TITLE
Discuss: how to "reset" a failed build, in order to prepare for a new one?

### ISSUE THREAD

**Issue by afred** [WGBH/aws-wrapper#42]
After getting some failures during a build, there's a lot of stuff to undo before you can try a new build using the same parameters (mainly the `name` parameters).

Not sure if there are clean ways to undo everything that has been done, but the things I'm bumping into include:
  * key exists (on local machine)
  * key pair already exists (in AWS)
  * group already exists (in AWS)

maybe more. That's what I've seen so far.

**Comment by mccalluc** [comment]
@afred: `destroy.rb --unsafe` is what you want, I think? Reopen if I am misunderstanding.

**Comment by afred** [comment]
@mccalluc yep, i think i didn't know about the option when I made this ticket.
