### ISSUE TITLE
Cannot build with t2.medium instance type

### ISSUE THREAD

**Issue by afred** [WGBH/aws-wrapper#44]
When specifying `instance_type: "t2.medium"` in `defaults.yml`, I get the following error.

```
The specified instance type can only be used in a VPC. A subnet ID or network interface ID is required to carry out the request. (Aws::EC2::Errors::VPCResourceNotSpecified)
```

**Done when** I can run the build script with `t2.medium` instance type

**Comment by mccalluc** [comment]
@afred: do you see a value in getting VPC working, or are we happy enough with m3.medium?

**Comment by afred** [comment]
@mccalluc I know that AWS recommends using VPCs, but I'm not aware of what the downsides are if we don't. More reading required. Closing this, and we can open a new one once we identify a concrete need.
