### ISSUE TITLE
Relax errors when multiple reservations are returned

### ISSUE THREAD

**Issue by afred** [WGBH/aws-wrapper#57]
**Rationale:** I built a pair of instances, but it failed midway due to intermittent network connection. So I destroyed that pair, and tried to rebuild another, which worked. But then I couldn't retrieve the IPs using `scripts/ssh_opt.rb --name [name] --just_ips` because the SDK returned multiple "reservations".

Apparently the `destroy.rb` script created reservations for the instances it was terminating. And as we have seen, instances will stick around for an unknown amount of time with the state of "terminated". So too, it seems, will the reservation that terminated them.

So the presence of additional reservations does not necessarily mean things are in a bad state.

**Done when**
  * an error is _not_ thrown immediately upon finding that a request returns multiple reservations
  * rather, and an error _is_ thrown only when multiple reservations are returned that contain instances that are not in a "terminated" state.

**Comment by mccalluc** [comment]
Good idea. I'll try to make it work.

**Comment by mccalluc** [comment]
note: there are actually several states I've chosen to ignore: http://docs.aws.amazon.com/sdkforruby/api/Aws/EC2/Client.html#describe_instances-instance_method: `shutting-down` | `terminated` | `stopping` | `stopped`
