### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by mccalluc** [WGBH/aws-wrapper#7]

**Comment by mccalluc** [comment]
@afred: Could mock the AWS Clients and make sure our higher level wrapper methods induce the expected SDK calls.

Does this seem sufficient to you? Other possibilities:
- Capture the low level XML that's sent from SDK code and make sure it's what we expect, like we use [WebMock in the ci gem](https://github.com/WGBH/sony-ci-api/blob/master/spec/sony_ci_api_spec.rb#L175). Possible, but that low level stuff really isn't our concern. WebMock did work well, though, so this is nearly as easy as the first option.
- Actually make the live calls. Would lean against this for testing: The scripts just are really slow, waiting for records to propagate through AWS, and I'm still not really comfortable giving Travis the keys.

Thoughts?

**Comment by afred** [comment]
@mccalluc option 1 (mocking the AWS) client would cover our responsibilities I think. Using rspec-mock's `instance_double` ensures that you are mocking _actual_ methods. From there, setting up specs that looks something like this is probably what we want...
```ruby
```

**Comment by mccalluc** [comment]
Thanks: Looked a little bit at WebMock: Not impossible, but does require looking down into the structure of the XML responses from their API, which we wouldn't otherwise even be looking at. I'll shift gears.

**Comment by mccalluc** [comment]
So we decided to have essentially two levels of tests:
- At the low level, mock AWS and make sure the expected calls are being made.
- At the high level, outside of rspec, run all the scripts straight from the shell and make sure they work. (ie 0 status)
