### ISSUE TITLE
AAPB Demo URLs

### ISSUE THREAD

**Issue by jasoncorum** [WGBH/aws-wrapper#92]
After implementing and forcing accessing americanarchive.org over https, the regular http demo URL broke for the site: http://demo.aapb.wgbh-mla.org/. You now need to access here: https://demo.aapb.wgbh-mla.org/. But since we don't have an SSL cert for the domain you get a warning before being able to access the site. 

Done When
- [ ] We can serve the site up at a demo location for the LOC since they cannot access IP addresses.

**Comment by sroosa** [comment]
Resolved awhile ago
